version: "3.8"
services:
  web:
    image: fusion-map-web:latest
    volumes:
      - "./:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BASE_URL=http://localhost:5000
  api:
    image: fusion-map-api:latest
    ports:
      - "5000:8080"
  db:
    image: postgres:latest
    volumes:
      - ./fusionfortress.sql:/docker-entrypoint-initdb.d/fusionfortress.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
